### ISSUE TITLE
It does not send an email

### ISSUE THREAD

**Issue by mithatb** [weymann/MercedesMe-OH-Drops#1]
I am not receiving PIN email. Is there a problem with package?

**Comment by weymann** [comment]
> I am not receiving PIN email. Is there a problem with package?

@mithatb 
Yes, you are right. Unfortunately authorization has changed a bit in order to receive an email. Changed, but only for 4.2 version https://github.com/weymann/MercedesMe-OH-Drops/raw/main/drops/org.openhab.binding.mercedesme-4.2.0-SNAPSHOT.jar

**Comment by mithatb** [comment]
Thank you, it worked!!!
