### ISSUE TITLE
WebSocket returns HTTP error 418 since 2024-10-09 requiring a change in the API endpoint

### ISSUE THREAD

**Issue by fbomba6** [weymann/MercedesMe-OH-Drops#4]
Error details and symptoms in https://community.openhab.org/t/mercedes-me-binding/136852/212 and following posts.

The HTTP error suggest that the issue is with the Mercedes API endpoint, rather than with the adapter.

The home automation hub IObroker has a [similar Mercedes Me adapter](https://www.iobroker.net/#en/adapters/adapterref/iobroker.mercedesme/README.md) and I noticed that just two days ago [an update](https://github.com/TA2k/ioBroker.mercedesme/commit/52f7a6fc614c4e6282e420d7c6f8c71a7d98a56c) in the WebSocket endpoint was released, with an additional **v2** designator:
- `wss://websocket.emea-prod.mobilesdk.mercedes-benz.com/v2/ws`  instead of 
- `wss://websocket.emea-prod.mobilesdk.mercedes-benz.com/ws`

Hopefully this is a simple and quick fix for this adapter as well.

Thanks in advance!

**Comment by fbomba6** [comment]
Looks like this is where the change would have to be applied: https://github.com/openhab/openhab-addons/blob/6ec28a8ea2b2021678a2b9e3fd2a2dbf7d0db33e/bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/Constants.java#L315  assuming that the **v2** does not imply a functional change in the interface...

**Comment by andrewfg** [comment]
@weymann just pinging you in case you may have missed it.

**Comment by clown-m** [comment]
@weymann Pls. check the problem, that's the second time we could not get data of our stupid Mercedes API

**Comment by andrewfg** [comment]
It was fixed...

https://github.com/openhab/openhab-addons/pull/17594

**Comment by weymann** [comment]
Thanks, perfect! I'm off for several days with no ability to test!

I follow Rene Nulsch and there seems to be some upcoming changes regarding authorization:
https://github.com/ReneNulschDE/mbapi2020/releases/tag/v0.19.0

**Comment by weymann** [comment]
Tested now also on my side
